# Generated by Django 2.0.9 on 2018-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_intent_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='intent',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
