# Generated by Django 2.0.7 on 2018-11-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_entity_entityvalue_synonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='entity_value',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='name',
        ),
        migrations.AddField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('patterns', 'Patterns'), ('synonyms', 'Synonyms')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='entity_synonym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_synonym', to='nlp.EntityValue'),
        ),
        migrations.AddField(
            model_name='synonym',
            name='text',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='entityvalue',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitiy_values', to='nlp.Entity'),
        ),
    ]
