# Generated by Django 2.0.7 on 2018-12-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0007_auto_20181216_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('synonyms', 'Synonyms'), ('not-specified', 'Not-specified'), ('patterns', 'Patterns')], max_length=80, null=True),
        ),
    ]
