# Generated by Django 2.0.7 on 2018-12-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0008_auto_20181222_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('patterns', 'Patterns'), ('synonyms', 'Synonyms'), ('not-specified', 'Not-specified')], max_length=80, null=True),
        ),
    ]
