# Generated by Django 2.0.9 on 2019-01-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0010_auto_20181225_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='entity_name',
            new_name='name',
        ),
    ]
