# Generated by Django 2.0.9 on 2019-05-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0011_auto_20190108_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='AL_TestNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sib_order', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='nlp.AL_TestNode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AL_TestNodeSorted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.IntegerField()),
                ('val2', models.IntegerField()),
                ('desc', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='nlp.AL_TestNodeSorted')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('synonyms', 'Synonyms'), ('not-specified', 'Not-specified'), ('patterns', 'Patterns')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_value_name',
            field=models.CharField(max_length=128),
        ),
    ]
