# Generated by Django 2.0.9 on 2019-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0012_auto_20190512_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('patterns', 'Patterns'), ('synonyms', 'Synonyms')], max_length=80, null=True),
        ),
    ]
