# Generated by Django 2.0.9 on 2019-05-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nlp', '0013_auto_20190512_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sib_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nlp.Intent')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='nlp.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('example', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Responses', to='nlp.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='AL_TestNodeSorted',
            new_name='NodeSorted',
        ),
        migrations.RemoveField(
            model_name='al_testnode',
            name='parent',
        ),
        migrations.DeleteModel(
            name='AL_TestNode',
        ),
    ]
