# Generated by Django 2.0.9 on 2019-05-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0014_auto_20190512_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('synonyms', 'Synonyms'), ('not-specified', 'Not-specified'), ('patterns', 'Patterns')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nlp.Intent'),
        ),
    ]
