# Generated by Django 2.0.9 on 2019-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0016_auto_20190601_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('patterns', 'Patterns'), ('synonyms', 'Synonyms')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='sib_order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
