# Generated by Django 2.0.9 on 2019-10-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0017_auto_20190607_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('synonyms', 'Synonyms'), ('not-specified', 'Not-specified'), ('patterns', 'Patterns')], max_length=80, null=True),
        ),
    ]
