# Generated by Django 2.0.9 on 2019-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0020_auto_20191019_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AlterField(
            model_name='entityvalue',
            name='entity_type',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('synonyms', 'Synonyms'), ('patterns', 'Patterns')], max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
